# Generated by Django 4.0 on 2023-04-04 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_1', models.FloatField(blank=True, default=0.0, null=True)),
                ('rate_2', models.FloatField(blank=True, default=0.0, null=True)),
                ('rate_3', models.FloatField(blank=True, default=0.0, null=True)),
                ('rate_4', models.FloatField(blank=True, default=0.0, null=True)),
                ('rate_5', models.FloatField(blank=True, default=0.0, null=True)),
                ('total', models.FloatField(blank=True, default=0.0, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradval.companydetail')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, max_length=160, null=True)),
                ('have_review', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradval.companydetail')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradval.companyevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradval.companydetail')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradval.companyevaluation')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradval.companyreviews')),
            ],
        ),
    ]
