# Generated by Django 4.0 on 2023-04-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradval', '0002_companyevaluation_companyreviews_companyactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLookUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
