# Generated by Django 4.0 on 2023-04-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradval', '0003_companylookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyevaluation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyevaluation',
            name='hs_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
