# Generated by Django 4.0 on 2023-04-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradval', '0004_companyevaluation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyevaluation',
            name='ref_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyevaluation',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
