# Generated by Django 4.0 on 2023-04-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradval', '0005_companyevaluation_ref_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyevaluation',
            name='ref_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
