# Generated by Django 4.0 on 2023-04-05 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradval', '0007_alter_companyactivity_evaluation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_date', models.CharField(blank=True, max_length=20, null=True)),
                ('notif', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='tradval.companydetail')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='tradval.companydetail')),
            ],
        ),
        migrations.AddField(
            model_name='companyactivity',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradval.evaluationrequest'),
        ),
    ]
