# Generated by Django 4.0 on 2023-04-05 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradval', '0008_evaluationrequest_companyactivity_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyClaims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_date', models.CharField(blank=True, max_length=20, null=True)),
                ('notif', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradval.companydetail')),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradval.companyevaluation')),
                ('reviews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradval.companyreviews')),
            ],
        ),
        migrations.AddField(
            model_name='companyactivity',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradval.companyclaims'),
        ),
    ]
